## Examen 2

A) Integral

In [ ]:
import random
import numpy as np
import pandas as pd
from scipy.integrate import quad

In [ ]:
# A.1 Creacion del numero aleatorio.
random.seed(1000305547)
n = random.randint(2,20)

#A.2 Solucion para la integral.
inicial = 0
final = 1.6

def funcion(x):
  return np.sin(x**13)

integral,error = quad(funcion, inicial, final)

print(integral)
print(error)

0.11596567361486147
7.204203797865955e-09


Como la funcion $sin(x^{13})$ tiene un movimiento "suave" entre, aproximadamente, -1.6 y 1.6. Se puede hallar la integral tranquilamente en el programa, desde 0 a 1.6. Pero desde 1.6 en adelante la funcion comienza a fluctuar mucho, lo cual general problemas en el programa para realizar el calculo.

Esto mismo sucede con el lado negativo de la funcion, pues es una funcion simetrica.

B) Matriz

In [ ]:
# Lectura del archivo y creacion del dataframe.
df = pd.read_json('https://raw.githubusercontent.com/ComputationalMethods/Evaluacion_2022-1/main/data/lista_pares.json')
dataframe = df.iloc[47]
print('Lista: ',dataframe.lista)
print('Pares: ',dataframe.pares)

Lista:  [2, -3, -5, 6, -11, 12, 12, -13]
Pares:  {'S': 1, 'ψ': [[-5, 6], [12, -13], [-11, 12], [2, -3], [6, -5], [-13, 12], [12, -11], [-3, 2]]}


In [ ]:
# B.1 Creacion de la matriz.
matriz = np.zeros([8,8])

for fil, i in enumerate(dataframe.lista):
  for colum, j in enumerate(dataframe.lista):
    if [i,j] in dataframe.pares['ψ']:
      matriz[fil,colum] = round(random.random(),3)

matriz

array([[0.   , 0.982, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.675, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.6  , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.207, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.953, 0.164, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.997, 0.   , 0.   , 0.123],
       [0.   , 0.   , 0.   , 0.   , 0.087, 0.   , 0.   , 0.802],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.226, 0.657, 0.   ]])

In [ ]:
# B.2 Calculo del determinante.
det = np.linalg.det(matriz)
print(r'El determinante es: %.f. Por tanto debe haber, como minimo, una fila de ceros.'%det)

El determinante es: 0. Por tanto debe haber, como minimo, una fila de ceros.


In [ ]:
# B.3 Ordenamiento de autovalores y autovectores.
autovalor, autovector = np.linalg.eig(matriz)

a_valor_abs = [abs(ele) for ele in autovalor]
a_valor_abs.sort()
indice = np.argsort(a_valor_abs)
autovector = autovector[:,indice]

print('''Autovalores ordenados:
''', np.round(np.diag(a_valor_abs),3))
print('''
Autovectores ordenados:
''', np.around(autovector, 3))

Autovalores ordenados:
 [[0.352 0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.352 0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.652 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.652 0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.814 0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.814 0.    0.   ]
 [0.    0.    0.    0.    0.    0.    1.046 0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.046]]

Autovectores ordenados:
 [[ 0.77  -0.77   0.     0.     0.     0.     0.     0.   ]
 [ 0.638  0.638  0.     0.     0.     0.     0.     0.   ]
 [ 0.     0.     0.862 -0.862  0.     0.     0.     0.   ]
 [ 0.     0.     0.506  0.506  0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.     0.628 -0.273 -0.628 -0.273]
 [ 0.     0.     0.     0.    -0.637  0.306 -0.637 -0.306]
 [ 0.     0.     0.     0.    -0.304 -0.693 -0.304  0.693]
 [ 0.     0.     0.     0.     0.328  0.593 -0.328  0.593]]


In [ ]:
# B.4
print('''Autovalores con valor absoluto: 
''', np.round(np.diag(a_valor_abs),3))
print('''
De la anterior matriz, podemos deducir que existen 4 autovalores degenerados, pues hay 4 autovalores que se repiten en la matriz''')

Autovalores con valor absoluto: 
 [[0.352 0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.352 0.    0.    0.    0.    0.    0.   ]
 [0.    0.    0.652 0.    0.    0.    0.    0.   ]
 [0.    0.    0.    0.652 0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.814 0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.814 0.    0.   ]
 [0.    0.    0.    0.    0.    0.    1.046 0.   ]
 [0.    0.    0.    0.    0.    0.    0.    1.046]]

De la anterior matriz, podemos deducir que existen 4 autovalores degenerados, pues hay 4 autovalores que se repiten en la matriz
